### ISSUE TITLE
Add Products Button not working on Home

### ISSUE THREAD

**Issue by SabryShawally** [rihan-a/JS-rihan-Ecommerce#1]
**Description** 
Clicking the add products button on the home page doesn’t work

**How To Reproduce**
1. Open up the website 
2. Scroll to any product 
3. Click the add button

**Expected Outcome** 
- The clicked products are added to the cart
- The cart price is updated

**Actual Outcome**
The clicked products are not added to the cart

**Environment**
Device: iPhone 13 or iPad 11 Pro
Browser: Embedded Browser
OS Version: iOS 15.6
Occurrence: all the time 10/10

**Comment by rihan-a** [comment]
This bug is fixed
